### ISSUE TITLE
Missing artifacts for Ubuntu 20.04

### ISSUE THREAD

**Issue by KoeMai** [muhkuh-sys/org.muhkuh.lua-jonchki#1]
I try to build "org.muhkuh.tools-flasher". The build process fails with following log message

```
INFO:root:Install jonchki v0.0.3.1 to /tmp/org.muhkuh.tools-flasher/targets.
INFO:root:Host CPU architecture: x86_64
INFO:root:Host distribution ID: ubuntu
INFO:root:Host distribution version: 20.04
INFO:root:Standard archive format: tar.gz
DEBUG:root:Jonchki path: /tmp/org.muhkuh.tools-flasher/targets/jonchki-0.0.3.1
DEBUG:root:Jonchki tool: /tmp/org.muhkuh.tools-flasher/targets/jonchki-0.0.3.1/jonchki
DEBUG:root:Jonchki-light path: /tmp/org.muhkuh.tools-flasher/targets/jonchki-light-0.0.3.1
DEBUG:root:Jonchki-light tool: /tmp/org.muhkuh.tools-flasher/targets/jonchki-light-0.0.3.1/jonchki.lua
INFO:root:The jonchki path does not exist.
INFO:root:The jonchki-light path does not exist.
INFO:root:The tool is not yet installed in the requested version.
INFO:root:Trying to download "https://github.com/muhkuh-sys/org.muhkuh.lua-jonchki/releases/download/v0.0.3.1/jonchki-0.0.3.1-ubuntu20.04_x86_64.tar.gz".
Failed to download https://github.com/muhkuh-sys/org.muhkuh.lua-jonchki/releases/download/v0.0.3.1/jonchki-0.0.3.1-ubuntu20.04_x86_64.tar.gz: 404
INFO:root:Trying to download "https://github.com/muhkuh-sys/org.muhkuh.lua-jonchki/releases/download/v0.0.3.1/jonchki-light-0.0.3.1.zip".
Size in bytes: 242356
  0% ..................................................
 42% ..................................................
 84% ..................
INFO:root:The jonchki-light path does not exist.
Traceback (most recent call last):
  File "build_artifact.py", line 133, in <module>
    sys.exit(subprocess.call(astrArguments, cwd=strCfg_workingFolder))
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
AttributeError: 'NoneType' object has no attribute 'rfind'
```

Most of the required repository contains a build result for ubuntu_20.04, in this repository they are missing.

**Comment by docbacardi** [comment]
The flasher version in this repository still uses Jonchki v0.0.3.1, which supports Ubuntu up to 18.04 . It is still possible to use the 18.04 binaries on 20.04: 

```
JONCHKI_URL_OVERWRITE=https://github.com/muhkuh-sys/org.muhkuh.lua-jonchki/releases/download/v0.0.3.1/jonchki-0.0.3.1-ubuntu18.04_x86_64.tar.gz ./build_artifact.py ubuntu 18.04 x86_64
```
This builds an Ubuntu 18.04 version on 20.04 .
